# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GNWrapperAdSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GNWrapperAdSampleApp
  # Google ad SDK
  pod 'Google-Mobile-Ads-SDK'
  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/RemoteConfig'
  # Prebid
  pod 'PrebidMobile'
  # PubMatic
  pod 'OpenWrapSDK'
  pod 'OpenWrapEventHandler/DFP'
  # GNWrapperAdSdk
  pod 'Geniee-Wrapper-Ad-SDK-iOS'
  # GNHBPrebidBannerAdapter
  pod 'Geniee-Wrapper-Ad-Banner-Adapter-Prebid-iOS'
  # GNHBPubmaticBannerAdapter
  pod 'Geniee-Wrapper-Ad-Banner-Adapter-Pubmatic-iOS'

end
